$pdf_previewer = "xdg-open";
$out_dir = "build";
$pdflatex = "lualatex -interaction=nonstopmode --shell-escape -halt-on-error %O %S";
$pdf_mode = 1;
add_cus_dep('glo', 'gls', 0, 'makeglossaries');
add_cus_dep('acn', 'acr', 0, 'makeglossaries');
sub makeglossaries {
   $dir = dirname($_[0]);
   $file = basename($_[0]);
   system( "makeglossaries", "-d", $dir, $file);
}

push @generated_exts, "bcf bbl";
$clean_ext = "acr acn alg bcf bbl glg glo gls run.xml xdy snm nav";
